FROM --platform=$TARGETPLATFORM python:3.11.4-slim-bookworm AS build

WORKDIR /app

COPY pyproject.toml  /app
RUN  pip3 install .[transform]

COPY ./src/transform.py /app/
COPY ./src/common/*.py /app/common/

CMD [ "python3", "transform.py" ]
